[build]
cmds = [
  "dotnet restore GerenciadorHotel.csproj",
  "dotnet publish GerenciadorHotel.csproj --configuration Release --output /app/publish --no-restore"
]

[start]
cmd = "dotnet /app/publish/GerenciadorHotel.dll"
